container.resources.cpu = CPU requested for the operator.
container.resources.memory = Memory allocated to the operator.
image.repository = Image repository.
image.tag = Image tag.
image.pullPolicy = Image pull policy.
image.pullSecrets = Image pull secret(s) (as a JSON array).
nodeSelector = Node selector JSON object if any.
persistence.storage = Storage size for the operator.
security.id = Identifier used for the user, group and filesystem.
tolerations = Tolerations as a JSON array if any.
affinity = Affinity as a JSON object if any.
