generic-job.activeDeadlineSeconds = TBD
generic-job.affinity = TBD
generic-job.annotations = TBD
generic-job.args = TBD
generic-job.automountServiceAccountToken = TBD
generic-job.backoffLimit = TBD
generic-job.containerSecurityContext = TBD
generic-job.cpu = TBD
generic-job.dnsConfig = TBD
generic-job.env = TBD
generic-job.image = TBD
generic-job.imagePullPolicy = TBD
generic-job.imagePullSecrets = TBD
generic-job.initContainers = TBD
generic-job.labels = TBD
generic-job.memory = TBD
generic-job.name = TBD
generic-job.nodeSelector = TBD
generic-job.podAnnotations = TBD
generic-job.podLabels = TBD
generic-job.podSecurityContext = TBD
generic-job.resources = TBD
generic-job.restartPolicy = TBD
generic-job.serviceAccountName = TBD
generic-job.tolerations = TBD
generic-job.ttlSecondsAfterFinished = TBD
