<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.yupiik.gatling</groupId>
    <artifactId>gatling-operator</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>documentation</artifactId>
  <name>Gatling Operator :: Documentation</name>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gatling-operator-controller</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gatling-cli</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>deployment</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.yupiik.fusion</groupId>
      <artifactId>fusion-documentation</artifactId>
      <version>${yupiik-fusion.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/minisite</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <!-- mvn [compile] yupiik-tools:serve-minisite -e -->
        <groupId>io.yupiik.maven</groupId>
        <artifactId>yupiik-tools-maven-plugin</artifactId>
        <configuration>
          <preferYupiikAsciidoc>true</preferYupiikAsciidoc>
          <siteBase>//www.yupiik.io/gatling-operator</siteBase>
          <title>Gatling Operator</title>
          <description>${project.parent.description}</description>
          <indexText>Gatling Operator</indexText>
          <indexSubTitle>${project.parent.description}</indexSubTitle>
          <logoText>Yupiik Gatling Operator</logoText>
          <logoSideText>Documentation</logoSideText>
          <copyright>© 2025 &lt;strong&gt;&lt;a href="https://www.yupiik.com"&gt;Yupiik&lt;/a&gt;&lt;/strong&gt;. All Rights Reserved</copyright>
          <attributes>
            <partialsdir>${project.basedir}/src/main/minisite/content/_partials</partialsdir>
          </attributes>
          <templateExtensionPoints>
            <socialLinks>&lt;li class="list-inline-item"&gt;&lt;a title="LinkedIn" target="_blank" href="https://www.linkedin.com/company/yupiik/"&gt;&lt;i class="fab fa-linkedin fa-fw"&gt;&lt;/i&gt;&lt;/a&gt;&lt;/li&gt;
              &lt;li class="list-inline-item"&gt;&lt;a title="Twitter" target="_blank" href="https://twitter.com/Yupiik/"&gt;&lt;i class="fab fa-twitter fa-fw"&gt;&lt;/i&gt;&lt;/a&gt;&lt;/li&gt;
              &lt;li class="list-inline-item"&gt;&lt;a title="Github" target="_blank" href="https://www.github.com/yupiik/fusion"&gt;&lt;i class="fab fa-github fa-fw"&gt;&lt;/i&gt;&lt;/a&gt;&lt;/li&gt;</socialLinks>
          </templateExtensionPoints>
          <preActions>
            <preAction>
              <type>io.yupiik.fusion.documentation.DocumentationGenerator</type>
              <configuration>
                <includeEnvironmentNames>true</includeEnvironmentNames>
                <formatter>definitionlist</formatter>
              </configuration>
            </preAction>
            <preAction>
              <type>io.yupiik.fusion.documentation.CliDocumentationGenerator</type>
            </preAction>
          </preActions>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>io.yupiik.maven</groupId>
            <artifactId>asciidoc-java</artifactId>
            <version>${yupiik-tools.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>buildDoc</id>
            <goals>
              <goal>minisite</goal>
            </goals>
            <phase>prepare-package</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <!-- todo: deploy minisite
    <profile>
      <id>ci.build</id>
      <activation>
        <property>
          <name>ci.build</name>
          <value>true</value>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>io.yupiik.maven</groupId>
            <artifactId>yupiik-tools-maven-plugin</artifactId>
            <configuration>
              <git>
                <ignore>false</ignore>
                <noJekyll>false</noJekyll>
                <serverId>gh-pages</serverId>
                <branch>refs/heads/gh-pages</branch>
                <url>${env.xxxx}</url>
              </git>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    -->
  </profiles>
</project>
